copy "BFA\code.lua" "Battle For Azeroth\Tol Dagor\code.lua"
copy "BFA\rotation.lua" "Battle For Azeroth\Tol Dagor\rotation.lua"
copy "BFA\utils.lua" "Battle For Azeroth\Tol Dagor\utils.lua"
copy "BFA\code.lua" "Battle For Azeroth\Aqir\code.lua"
copy "BFA\rotation.lua" "Battle For Azeroth\Aqir\rotation.lua"
copy "BFA\utils.lua" "Battle For Azeroth\Aqir\utils.lua"
copy "BFA\code.lua" "Battle For Azeroth\Freehold\code.lua"
copy "BFA\rotation.lua" "Battle For Azeroth\Freehold\rotation.lua"
copy "BFA\utils.lua" "Battle For Azeroth\Freehold\utils.lua"
copy "BFA\code.lua" "Battle For Azeroth\Underrot\code.lua"
copy "BFA\rotation.lua" "Battle For Azeroth\Underrot\rotation.lua"
copy "BFA\utils.lua" "Battle For Azeroth\Underrot\utils.lua"